=== ImTeijirr/TuxLetterGame/src/xml/dicoSchema.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.thedico.fr"
           xmlns="http://www.thedico.fr"
           elementFormDefault="qualified">

    <xs:element name="dico" type="Dico"/>
    <xs:complexType name="Dico">
        <xs:sequence>
            <xs:element name="mot" type="Mot" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Mot">
        <xs:sequence>
            <xs:element name="valeur" type="Valeur"/>
            <xs:element name="difficulte" type="Difficulte"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="Valeur">
        <xs:restriction base="xs:string">  
            <xs:pattern value="\w\w\w*"/>
        </xs:restriction>
    </xs:simpleType>
        <xs:simpleType name="Difficulte">
        <xs:restriction base="xs:int">  
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ImTeijirr/TuxLetterGame/src/xml/dico.xml
<?xml version="1.0" encoding="UTF-8"?>

<dico xmlns="http://www.thedico.fr"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.thedico.fr dicoSchema.xsd">
    <mot>
        <valeur>Salut</valeur> 
        <difficulte>1</difficulte>
    </mot>
        <mot>
        <valeur>cle</valeur> 
        <difficulte>1</difficulte>
    </mot>
    <mot>
        <valeur>Yo</valeur> 
        <difficulte>1</difficulte>
    </mot>
    <mot>
        <valeur>Coucou</valeur> 
        <difficulte>1</difficulte>
    </mot>
    <mot>
        <valeur>Voiture</valeur> 
        <difficulte>2</difficulte>
    </mot>
    <mot>
        <valeur>indice</valeur> 
        <difficulte>2</difficulte>
    </mot>
    <mot>
        <valeur>Covoiturage</valeur> 
        <difficulte>3</difficulte>
    </mot>
    <mot>
        <valeur>Theiere</valeur> 
        <difficulte>4</difficulte>
    </mot>
    <mot>
        <valeur>Rhapsodie</valeur> 
        <difficulte>5</difficulte>
    </mot>
</dico>
